=== MayurCodes2508/market-analytics-platform/el_system/schemas/root_schema.json
{
    
    "$schema": "https://json-schema.org/draft/2020-12/schema",

    "type": "object",

    "required": ["job_name", "system", "job_type", "sub_jobtype", "exec"],

    "properties": {

        "job_name": {

            "type": "string",
            "pattern": "^(dev_|prod_)[a-z0-9_]+$",
            "minLength": 7,
            "maxLength": 30
        },

        "system": {

            "type": "string",
            "minLength": 1,
            "maxLength": 30
        },

        "job_type": {

            "type": "string",
            "minLength": 1,
            "maxLength": 30
        },

        "sub_jobtype": {

            "type": "string",
            "minLength": 1,
            "maxLength": 30
        },

        "metadata": {

            "type": "object",

            "required": ["source", "dataset", "entity"],

            "properties": {

                "source": {

                    "type": "string",
                    "minLength": 1,
                    "maxLength": 30
                },

                "dataset": {

                    "type": "string",
                    "minLength": 1,
                    "maxLength": 30
                },

                "entity": {

                    "type": "string",
                    "minLength": 1,
                    "maxLength": 30
                }
            },

            "additionalProperties": false
        },

        "exec": {

            "$ref": "exec_schemas/api_exec_schema.json"
        },

        "dest": {

            "$ref": "dest_schemas/gcs_dest_schema.json"
        }
    },

    "allOf": [
        {

            "if": {

                "properties": {

                    "job_type": {"const": "ingestion"}
                }
            },

            "then": {

                "required": ["dest"]
            }
        },

        {

            "if": {

                "properties": {

                    "dest": {

                        
                    }
                }
            },

            "then": {

                "required": ["metadata"]
            }
        }
    ],
    
    "additionalProperties": false
}

=== MayurCodes2508/market-analytics-platform/el_system/configs/job/coingecko_sources/dev/market_price.json
{
    "job_name": "dev_coingecko_market_price",

    "system": "el",

    "job_type": "ingestion",

    "sub_jobtype": "api",

    "metadata": {

        "source": "coingecko",
        "dataset": "market_price",
        "entity": "cryptocurrency"
    },

    "exec": {

        "exec_type": "ApiExecCmd",
        "base_url": "https://api.coingecko.com/api/v3",
        "path": "/coins/markets",
        "pagination": {

            "strategy": "page",
            "page_param": "page"
        },

        "page_size": {

            "param": "per_page",
            "value": 50
        },

        "query_params": {

            "vs_currency": "inr"
        },

        "auth": {

            "auth_type": "api_key",
            "key_env": "COINGECKO_API_KEY",
            "location": "header",
            "name": "x-cg-demo-api-key"
        }
    },

    "dest": {

        "dest_type": "GCS",
        "bucket": "dev-market-analytics-platform-bucket",
        "layer": "dev",
        "format": "parquet",
        "path_template": "{layer}/{source}/{dataset}/{entity}/ingestion_dt={ingestion_dt}/ingestion_ts={ingestion_ts}.{format}"
    }
}
